version: '3.3'
volumes:
  jenkins-home:
  mongo:

services:
  ui:
    image: delt0p/pool-ui:latest
    build: 
      context: ../ui/poolmanage-ui
      dockerfile: Dockerfile
    ports:
    - target: 80
      published: 80
    depends_on:
    - jenkins
    - api
 
  api:
     image: delt0p/pool-api:latest 
     build:
       context: ./poolmanager-api
       dockerfile: Dockerfile
     depends_on:
     - mongo

  mongo:
     image: mongo:latest
     volumes: 
     - type: volume
       source: mongo
       target: /data/db

  jenkins:
     image: bobcrutchley/jenkins:latest
     volumes: 
     - type: volume
       source: jenkins-home
       target: /var/jenkins_home
     - type: bind
       source: /var/run/docker.sock
       target: /var/run/docker.sock
     environment:
     - JENKINS_OPTS="--prefix=/jenkins"
